stateDiagram-v2
    direction TB

    state "active" as active
    state "closed" as closed

    [*] --> active : PesanPertamaTamu<br>[Cookie UUID Valid]<br>/ Hash Token & Sesi 30 Hari

    active --> closed : TutupObrolan<br>/ Inject ___CHAT_CLOSED___

    closed --> active : KirimBalasanAdmin<br>/ Reopen Thread Chat

    closed --> [*] : SchedulerPrune<br>[t > 90 Hari]<br>/ chat-guest:prune (Hapus)

    closed --> [*] : AdminHapusManual<br>/ Force Delete Thread
