stateDiagram-v2
    direction TB

    state "tersedia" as tersedia
    state "maintenance" as maintenance

    [*] --> tersedia : Tambah Kamar Baru<br>[Data Valid] / Simpan Unit

    state "terisi" as terisi {
        Dihuni : Dihuni Penyewa Aktif
        InspeksiFisik : Hold Inspeksi Fisik Kamar
        Dihuni --> InspeksiFisik : Checkout Penyewa<br>[Tahan Status 'terisi']
    }

    tersedia --> Dihuni : Reservasi / Registrasi<br>/ Pindah Masuk

    InspeksiFisik --> tersedia : Inspeksi OK<br>[Fasilitas Utuh]<br>/ Bebaskan Unit
    InspeksiFisik --> maintenance : Ditemukan Kerusakan<br>/ Unit Diperbaiki

    tersedia --> maintenance : Perawatan Rutin<br>/ Pemeliharaan Fasilitas
    maintenance --> tersedia : Perbaikan Selesai<br>/ Buka Unit Tersedia

    tersedia --> [*] : Hapus Kamar [Tanpa Penyewa]<br>/ Soft Delete Unit
